### ISSUE TITLE
Experience: Expose version number in Web UI

### ISSUE THREAD

**Issue by elliotxx** [KusionStack/karpor#362]
### What would you like to be added?

Expose version number in Web UI. The effect is similar: 

![image](https://github.com/KusionStack/karpor/assets/9360247/18d24a10-193c-454c-a8c3-8bc89d60504a)

You can get the `version number` from `/server-configs`. Such as: https://[karpor-demo.kusionstack.io/server-configs](https://karpor-demo.kusionstack.io/server-configs)

![image](https://github.com/KusionStack/karpor/assets/9360247/0a0a224d-1864-4773-926a-c90fad44ac41)

The current version number has not been added to this API Response. If you claim this issue, we will do it as soon as possible to support you in completing this issue.

### Why is this needed?

Clearly inform the user of the currently deployed Karpor version.

**Comment by solarhell** [comment]
I can't figure out where the version number stored, maybe can use a static file to store it, and use `embed` package to make it compiled with binary, and publish it via `expvar`.

**Comment by elliotxx** [comment]
@solarhell Yes, implementing this issue actually requires two steps:
1. Record the current version in each distribution and expose it through `/server-configs` by `expvar`
2. The front-end is obtained from the `/server-configs`, and it is displayed

**Comment by elliotxx** [comment]
@solarhell Hi, are you interested in this issue?

**Comment by solarhell** [comment]
@elliotxx ok, please assign it to me.

**Comment by elliotxx** [comment]
@solarhell Welcome 👋, I have assigned it to you. If you need help, feel free to discuss.

**Comment by solarhell** [comment]
@elliotxx https://github.com/KusionStack/karpor/pull/531
I'm not familiar with react and css, so the front-end section simply shows the text.

**Comment by elliotxx** [comment]
@solarhell You're so efficient! 👍 
I saw the implementation of PR, which requires manual maintenance of VERSION file. It would be even better if the version number could be automatically calculated through `go generate` before `go build`, but the current approach is enough, no need to be too complicated.
I can ask front-end contributor to help optimize the display of version numbers, never mind.

**Comment by elliotxx** [comment]
@hai-tian Hi, can you help optimize the `version box`, just like `read-only mode box`.

**Comment by solarhell** [comment]
@elliotxx Yes, i check the code and see the `goreleaser` which retrieves the version number from the git tag. In the development period, we are on the develop branch, so the tag and version number is empty.

**Comment by elliotxx** [comment]
@elliotxx OK, I have checked the PR content and there are no other problem. I merge PR first, and then ask @hai-tian to submit the front-end optimized PR on the main branch.

**Comment by elliotxx** [comment]
@solarhell Hi, the PR #533  with the version number style optimization has been merged. You can view the latest effect in [Live Demo](https://karpor-demo.kusionstack.io/).

**Comment by elliotxx** [comment]
I have created a new issue for future optimization. #537
