### ISSUE TITLE
Bug(server): Unable to access /docs/index.html endpoint (404)

### ISSUE THREAD

**Issue by elliotxx** [KusionStack/karpor#440]
### What happened?

Unable to access /docs/index.html endpoint.

![image](https://github.com/KusionStack/karpor/assets/9360247/b3ec9061-68cb-4e4d-9645-df7b3024e922)

### What did you expect to happen?

Can be visited normally.

### How can we reproduce it (as minimally and precisely as possible)?

Access `https://karpor-demo.kusionstack.io/docs/index.html` in browser

### Karpor version

<details>

```console
$ karpor -V
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

**Comment by solarhell** [comment]
I want to claim this task.

**Comment by elliotxx** [comment]
> I want to claim this task.

@solarhell Welcome! 👋 I have assigned this issue to you. If you need to provide other information or help, you can @me any time.

**Comment by elliotxx** [comment]
@solarhell Hi 👋 Is there any problem?

**Comment by solarhell** [comment]
@elliotxx It's been a little busy the last couple days but I'm still working on it

**Comment by elliotxx** [comment]
@solarhell Sure, busy you first. If you've got any puzzling queries, feel free to have a chat in this issue.

**Comment by solarhell** [comment]
It seems that doc works fine when i use helm install. Maybe the helm package version used in demo env is old.

<img width="1169" alt="image" src="https://github.com/KusionStack/karpor/assets/10279583/ea91acb2-4e7f-466f-8ee5-bec49043b890">

**Comment by elliotxx** [comment]
@solarhell Let me confirm again. Actually, the latest version is also used in LiveDemo.

**Comment by elliotxx** [comment]
@solarhell Yes, it's really okay. Sorry, take up your time.
