### ISSUE TITLE
Feat: Support cluster health status check and delay calculation

### ISSUE THREAD

**Issue by elliotxx** [KusionStack/karpor#457]
### What would you like to be added?

- The cluster model increases the health status and delay of the cluster.

- Start the timing task to calculate the health status and delay of the cluster

- The front-end interface shows health status and delay

### Why is this needed?

Enhance the experience of multi-cluster management

**Comment by z1cheng** [comment]
@elliotxx Can I work on this issue? 👀

**Comment by elliotxx** [comment]
@z1cheng Of course, very welcome! 🚀 If you need help, feel free to ping me or @ruquanzhao anytime.

**Comment by elliotxx** [comment]
@z1cheng Hi did you encounter any problems during the implementation of this issue?

**Comment by elliotxx** [comment]
@z1cheng Sad 💔 ... Welcome back when you have time
