### ISSUE TITLE
Experience: k8s automatic injection fields such as managedFields need to be ignored on YAML page

### ISSUE THREAD

**Issue by elliotxx** [KusionStack/karpor#461]
### What would you like to be added?

K8s automatic injection fields such as managedFields need to be ignored on YAML page.

### Why is this needed?

There is too much invalid information when viewing the resource yaml.

**Comment by elliotxx** [comment]
@T1-leiyang Welcome 👋, I have assigned it to you. If you need help, feel free to discuss.

**Comment by elliotxx** [comment]
@T1-leiyang Hi 👋 Is there any problem?

**Comment by elliotxx** [comment]
@regend Hi, can you leave a comment on this issue so that I can mark it as completed by you and you will appear on our [contribution list](https://github.com/KusionStack/karpor/issues/463)!

**Comment by regend** [comment]
clean the managedFields field may be a way to solve

**Comment by elliotxx** [comment]
Done

![Image](https://github.com/user-attachments/assets/d92cf0e2-02b9-49f6-99b0-109101edf671)
