### ISSUE TITLE
Test: supplementary unit tests for karpor server

### ISSUE THREAD

**Issue by elliotxx** [KusionStack/karpor#496]
### What would you like to be added?

Supplementary more unit tests for karpor server. The current project testing coverage is approximately 70%. You can execute the `make cover` to view it. The packages with zero coverage need to be supplemented with unit testing.

![image](https://github.com/KusionStack/karpor/assets/9360247/080bad20-4fca-4a3b-a941-ef9e824efd2f)

**NOTE**: When writing unit tests, you need to follow the [Code Conventions](https://www.kusionstack.io/karpor/developer-guide/conventions/code-conventions)

### Why is this needed?

Need to rely on unit testing to ensure the overall quality of the project.

**Comment by cheny-alf** [comment]
Can I take this up? :)

**Comment by elliotxx** [comment]
@cheny-alf Of course, very welcome! Before start, you can quickly read these two conventions: [Test Conventions](https://www.kusionstack.io/karpor/developer-guide/conventions/test-conventions) and [Code Conventions](https://www.kusionstack.io/karpor/developer-guide/conventions/code-conventions).
