### ISSUE TITLE
Experience: Whether the GitHub Badge is displayed through the flag in /server-configs

### ISSUE THREAD

**Issue by elliotxx** [KusionStack/karpor#501]
### What would you like to be added?

Whether the GitHub logo is displayed through the flag in /server-configs.

GitHub logo is used to jump to Karpor's github repo. Sometimes, users do not need this link. For example, when deploying within the company.

![image](https://github.com/KusionStack/karpor/assets/9360247/718ebd6a-3f8b-46c8-8cc2-b66a069db50b)

You can call the `$HOST/server-configs` in the front-end code to get the server configurations, including whether to display the github logo, which is set by the service deployer.

![image](https://github.com/KusionStack/karpor/assets/9360247/944cf18c-2a21-4974-9325-c047823acca5)

### Why is this needed?

Sometimes, users do not need this github logo. For example, when deploying within the company.

**Comment by elliotxx** [comment]
@CirillaQL Hi, can you leave a comment on this issue so that I can mark it as completed by you and you will appear on our [contribution list](https://github.com/KusionStack/karpor/issues/463)!

**Comment by CirillaQL** [comment]
> [@CirillaQL](https://github.com/CirillaQL) Hi, can you also reply here

Hi, thanks, but I don't remember making a commit on this issue. I don't know about this GitHub Badge thing 😂

**Comment by elliotxx** [comment]
@CirillaQL oh sorry I've read it wrong 🤦‍♂️

**Comment by z1cheng** [comment]
@elliotxx Sure, I appreciate the opportunity to contribute. Looking forward to collaborating again in the future.
