### ISSUE TITLE
karpor-server 添加resources 声明

### ISSUE THREAD

**Issue by Edwin-Li-01** [KusionStack/karpor#518]
### What would you like to be added?

请考虑一些小的开发机，不做资源限制，小的开发机可能都调度不出来pod

### Why is this needed?

部署体验

**Comment by elliotxx** [comment]
@Edwin-Li-01 很好的建议👍 我们之前记了 #347 用于提供更多安装选项，包括自定义更小的容器规格，现在已经把它放到下个版本规划中 [v0.5.0](https://github.com/KusionStack/karpor/milestone/4)，预计最近几个小版本就会 Release 这个功能，可以继续关注这个 issue
如果有其他使用问题也欢迎继续提需求 🎉

**Comment by elliotxx** [comment]
@Edwin-Li-01 这个 issue 提到的功能已经在 #519 中一起支持

**Comment by elliotxx** [comment]
@Edwin-Li-01 老哥，这个 issue 我先关掉了哈，如果有新的问题可以 reopen，或者在这个 helm 问题汇总的 issue 中统一跟进 #347
