### ISSUE TITLE
deployment 镜像声明优化

### ISSUE THREAD

**Issue by Edwin-Li-01** [KusionStack/karpor#519]
### What would you like to be added?

需要考虑有一些环境是不能通外网的，需要将镜像做一次内网转化，但是当前声明的image 还存在级联依赖，起初我转化了elasticsearch、karpor 两个镜像，但实际调度还存在golang:1.19 、quay.io/coreos/etcd:v3.5.11的镜像依赖，发现调度失败以后继续排查问题还存在两个镜像依赖，所以相信潜在的出现该问题的肯定不止我一个，需要将deployment声明对象进一步优化一下

### Why is this needed?

部署体验优化

**Comment by elliotxx** [comment]
@Edwin-Li-01 这个我们考虑这样优化，看下是不是 OK 👇
1. 提供国内镜像源，在中文文档中说明
2. 优化 Helm 包，将用到的所有镜像提供为安装参数，支持自定义镜像

**Comment by elliotxx** [comment]
@Edwin-Li-01 Hi 👋，久等了，我们优化了 Helm 包，提供了 20+ 自定义参数。现在上面两点都已支持，可以试用下：
1. 指定国内代理进行镜像加速，文档地址在[这里](https://www.kusionstack.io/zh/karpor/next/getting-started/installation#%E4%B8%AD%E5%9B%BD%E9%95%9C%E5%83%8F%E4%BB%A3%E7%90%86)：
```bash
helm repo update
helm install karpor-release kusionstack/karpor --set registryProxy=docker.m.daocloud.io
```
2. 通过 Helm 安装支持自定义镜像、副本数、资源规格，全部的自定义参数可以参考[文档](https://www.kusionstack.io/zh/karpor/next/getting-started/installation#chart-%E5%8F%82%E6%95%B0)：
```bash
helm repo update
helm install karpor-release kusionstack/karpor --set server.replicas=3 --set server.image.repo=<your_custom_registry>/karpor:latest --set server.etcd.resources.limits.memory=2Gi
```

**Comment by elliotxx** [comment]
@Edwin-Li-01  老哥，这个 issue 我先关掉了哈，如果有新的问题可以 reopen，或者在这个 helm 问题汇总的 issue 中统一跟进 https://github.com/KusionStack/karpor/issues/347
