### ISSUE TITLE
Feat: Support upload EKS cluster certificates

### ISSUE THREAD

**Issue by elliotxx** [KusionStack/karpor#521]
### What would you like to be added?

Support uploading EKS cluster certificates.

### Why is this needed?

Users uploading EKS certificates on the cluster management page will fail because EKS certificates will obtain tokens through the `aws` cli tool, which we currently do not support.

Related issue: #520

**Comment by elliotxx** [comment]
@CirillaQL completes this issue. Nice.

**Comment by elliotxx** [comment]
@CirillaQL Hi, can you leave a comment on this issue so that I can mark it as completed by you and you will appear on our [contribution list](https://github.com/KusionStack/karpor/issues/463)!

**Comment by CirillaQL** [comment]
OK, Thanks

**Comment by elliotxx** [comment]
Done~

![Image](https://github.com/user-attachments/assets/d8c23f23-a0d0-4012-a382-295b819bed5d)

![Image](https://github.com/user-attachments/assets/547325f3-6627-4088-8f79-9d5e90ca9048)
