### ISSUE TITLE
并非所有用户都有PVC，建议etcd支持hostPath Volume

### ISSUE THREAD

**Issue by Edwin-Li-01** [KusionStack/karpor#522]
### What would you like to be added?

sts资源etcd 依赖PVC 但未必所有用户的环境能够支持,建议适配支持hostPath Volume，PVC 可以作为高可用的方案建议

### Why is this needed?

部署优化

**Comment by elliotxx** [comment]
@Edwin-Li-01 Hi 我们已经将你提的这些需求加入到了 [v0.5.0 Milestone](https://github.com/KusionStack/karpor/milestone/4) 版本规划中，预计在本月月底正式发布，如果有关于这个版本更好的建议，欢迎在👉[论坛](https://github.com/KusionStack/karpor/discussions/528)👈中留言哈

**Comment by regend** [comment]
@elliotxx 我认为hostPath不应该直接在helm安装的时候就显示声明,因为sts的workload需要动态去创建,我们无法预知用户需要几个ectd副本. 想要做到动态的hostpath做好的方法是使用类似toplvm这样的本地存储CSI方案,karpor里需要做的只是去支持用户动态配置storageClass. 我这边提交了一个pr,麻烦看看https://github.com/KusionStack/charts/pull/50

**Comment by elliotxx** [comment]
@regend 感谢反馈和贡献！👍 我们先讨论一下，晚点给你反馈

**Comment by elliotxx** [comment]
用户提的 https://github.com/KusionStack/charts/pull/50 已合并，这个 Issue 先关闭了
