### ISSUE TITLE
感觉有点简单问题复杂化 建议使用 https://ki.xabc.io

### ISSUE THREAD

**Issue by ywgx** [KusionStack/karpor#524]
### What would you like to be added?

https://github.com/ywgx/ki

### Why is this needed?

可以对比一下看看 各自优缺点

**Comment by elliotxx** [comment]
@ywgx 看了下主要区别是 产品形态 不同， `ki` 的定位是“Kubectl Pro”，CLI 形态，适合作为个人运维工具在本地快捷管理集群，`karpor` 主要是 Web UI 形态，适合部署在公司或者小型机上面向内部平台或者开发者群体提供在线服务。
总的来说，面向的目标用户场景不同。
不过通过 `karpor` 签发的`多集群证书`+`kubectl`+`kubectx` 其实可以配置出类似 ki 的效果，我们有总结这方面的最佳实践：[告别集群证书切换，让你“一卡通行”](https://www.kusionstack.io/zh/karpor/user-guide/best-production-practices/one-pass-with-proxy)

**Comment by elliotxx** [comment]
@ywgx Hi 你有继续想讨论的观点吗 👋
