### ISSUE TITLE
karpor 部署问题

### ISSUE THREAD

**Issue by arrowfeng** [KusionStack/karpor#525]
### What happened?

hi，karpor 部署必须依赖 k8s 集群吗？如果只是一个 webui，是不是简单二进制启动就行了。

### What did you expect to happen?

感觉没必要为了 karpor 再去部署一个集群。

**Comment by elliotxx** [comment]
@arrowfeng 好问题，其实我们有在考虑提供 standalone 部署模式（在 #240 中探讨过）。
效果是只需要一个 binary 就可以本地启动，不依赖 k8s 和 docker，也可以通过 homebrew 等包管理工具一键安装。
当前版本的核心组件其实孵化于我们内部生产环境实践，所以部署会有一些门槛，我们会努力简化它。
