### ISSUE TITLE
本地部署开发环境，接入集群后资源拓扑为空

### ISSUE THREAD

**Issue by T1-leiyang** [KusionStack/karpor#532]
### What happened?

但我在本地环境部署的时候，通过helm方式部署，然后接入集群，集群拓扑为空，并且洞察报错resource group not found
<img width="1726" alt="image" src="https://github.com/user-attachments/assets/c6054a66-a097-47d3-8e8b-c62947893442">
<img width="1726" alt="image" src="https://github.com/user-attachments/assets/8ae485fa-e4ac-4aa3-be15-2fa21e34e567">

### What did you expect to happen?

希望能正常显示拓扑和集群资源

### How can we reproduce it (as minimally and precisely as possible)?

通过helm部署完成，访问ui接入集群

### Karpor version

<details>

```console
$ karpor -V
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

**Comment by T1-leiyang** [comment]
我部署完成之后还需做额外的操作么

**Comment by T1-leiyang** [comment]
看文档的话是不需要的，至少在洞悉的页面默认ns应该有数据

**Comment by elliotxx** [comment]
> 看文档的话是不需要的，至少在洞悉的页面默认ns应该有数据

@T1-leiyang 是的，理论上不需要其他额外步骤，我们尝试在本地复现下。你的集群证书通过 kubectl 可以正常获取资源吗？

**Comment by ruquanzhao** [comment]
@T1-leiyang 我这边本地没有复现出来，请问你的证书是不是有什么特殊的地方，可以用kubectl操作集群吗？

**Comment by adohe** [comment]
@T1-leiyang kind ping~

**Comment by elliotxx** [comment]
这个 Issue 先关闭，如果有需要再重新打开
