### ISSUE TITLE
Governance: Automatically calculate the current version number through Git

### ISSUE THREAD

**Issue by elliotxx** [KusionStack/karpor#537]
### What would you like to be added?

Automatically calculate the current version number through Git.

For example, assuming the latest tag is `v0.4.2`, if `HEAD` is equal to `v0.4.2`, then the version number is `v0.4.2`. If not equal, the version number is `v0.4.3-xxxxxx`, among them, `xxxxxx` is `${shortSha}`.

### Why is this needed?

The current version number is hardcode in the [pkg/version/VERSION](https://github.com/KusionStack/karpor/blob/main/pkg/version/VERSION) file, and its value needs to be manually modified before each new version is released, which is not conducive to long-term maintenance.

**Comment by rajeshkio** [comment]
Could you please confirm if this issue is still open and if I can start working on it?

**Comment by elliotxx** [comment]
@rajeshkio Yeah, this issue is currently not aasign to anyone. Welcome to claim it! Maybe you need to know some background of this feature. #362

**Comment by rajeshkio** [comment]
Thank you. I checked it. My idea is to create a directory 'scripts' and add a script to find the version number and update the pkg/version/VERSION. Is this the right approach or can you recommend any other way.

**Comment by elliotxx** [comment]
@rajeshkio I have an idea that has been validated in production here for your reference. The following example can generate version information and some git helpers, which should help you quickly implement this issue.
- https://github.com/elliotxx/go-web-template/blob/master/pkg/version/scripts/gen/gen.go
- https://github.com/elliotxx/go-web-template/blob/master/pkg/util/gitutil/gitutil.go

**Comment by rajeshkio** [comment]
ohh it looks like most of the things are already done. Let me try to build and see what is missing.

**Comment by elliotxx** [comment]
@rajeshkio Yes, some basic libraries can be reused. Looking forward to your PR!

**Comment by rajeshkio** [comment]
one silly question maybe. Should I directly import your libraries and use them or should I create new files with almost similar contents for this repo?

**Comment by elliotxx** [comment]
@rajeshkio Importing library `go-web-template` is not suitable. Can be directly copied into the project.

**Comment by rajeshkio** [comment]
Thought so. I will use the same structure and add or remove contents as needed.

**Comment by elliotxx** [comment]
@rajeshkio No problem, you can integrate according to actual needs. 👍

**Comment by elliotxx** [comment]
@rajeshkio Hi, I have created a new issue #560  for future optimization.
