### ISSUE TITLE
Extend Helm Chart

### ISSUE THREAD

**Issue by danielstankw** [KusionStack/karpor#548]
### What would you like to be added?

Add fields in the helm chart for persistence where user can define for example PVC, as well as fields for service, where the type can be adjusted.

### Why is this needed?

Makes tuning values.yaml easier

**Comment by elliotxx** [comment]
@danielstankw Thank you for your feedback! 👏 We just added some [chart parameters](https://www.kusionstack.io/karpor/next/getting-started/installation#chart-parameters) recently, but it doesn't seem enough.

I have linked your requirements to the #347 and we will optimize it as soon as possible.

**Comment by danielstankw** [comment]
Thank you

**Comment by elliotxx** [comment]
@danielstankw  Hi, these chart parameters are already supported, you can check them here:
https://www.kusionstack.io/karpor/next/getting-started/installation#chart-parameters
