### ISSUE TITLE
Feat: Add --version flag to output current version number

### ISSUE THREAD

**Issue by elliotxx** [KusionStack/karpor#560]
### What would you like to be added?

Add `--version` flag to output current version number.

```bash
$ karpor --version
v0.4.5
$ karpor -V
v0.4.5
```

### Why is this needed?

If I have Karpor's binary or image, unless it starts it, I can’t directly know its current version.

**Comment by rajeshkio** [comment]
I can take it, but will be busy for a few days. so will work on it at the weekends mostly.

**Comment by elliotxx** [comment]
@rajeshkio Brother, you're so cool. Yeah, you can start at convenience.
