### ISSUE TITLE
Installation: Fix the ErrImagePull of using helm to specify the server.image.tag

### ISSUE THREAD

**Issue by elliotxx** [KusionStack/karpor#561]
### What would you like to be added?

When I use helm specify the server.image.tag, it report an ErrImagePull error.

```bash
helm install karpor-release kusionstack/karpor --set server.image.tag=v0.4.5-beta.0
```

Error:

![image](https://github.com/user-attachments/assets/5afcb1c2-7ed1-4701-9f26-6aea14b05857)

Need to modify the [helm chart](https://github.com/KusionStack/charts/blob/master/charts/karpor/templates/_common.tpl#L5) to adapt to situations with the prefix 'v' of `server.image.tag`.

### Why is this needed?

Yeah

**Comment by z1cheng** [comment]
@elliotxx Created a PR https://github.com/KusionStack/charts/pull/46

**Comment by elliotxx** [comment]
> @elliotxx Created a PR [KusionStack/charts#46](https://github.com/KusionStack/charts/pull/46)

@z1cheng Coool, you're so fast

**Comment by elliotxx** [comment]
@z1cheng Welcome to become a new contributor! 🎉 https://github.com/KusionStack/karpor/pull/567
