### ISSUE TITLE
[Helm Install Error] Cluster unreachable: connection refused

### ISSUE THREAD

**Issue by cheny-alf** [KusionStack/karpor#563]
### What happened?

我在尝试按照 KarporStack 安装文档执行 `helm install karpor kusionstack/karpor` 命令时遇到了一个问题。我收到了以下错误消息：`Error: INSTALLATION FAILED: Kubernetes cluster unreachable: Get "http://localhost:8080/version": dial tcp 127.0.0.1:8080: connect: connection refused` 

<img width="1282" alt="image" src="https://github.com/user-attachments/assets/c9859ed1-c110-4722-b7af-6936c6452076">

### What did you expect to happen?

正常安装

### How can we reproduce it (as minimally and precisely as possible)?

v0.4 安装文档

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux VM-8-4-debian 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

**Comment by elliotxx** [comment]
@cheny-alf 收到，让我看看怎么回事

**Comment by elliotxx** [comment]
@cheny-alf 看起来这是 helm 的报错，原因是 helm install 的时候连不上目标 kubernetes 集群：
https://stackoverflow.com/questions/63066604/error-kubernetes-cluster-unreachable-get-http-localhost8080-versiontimeou

可以先用 `kubectl cluster-info `确定下 k8s 集群的连通性，或者检查是不是没有指定 `KUBECONFIG` 环境变量。

**Comment by cheny-alf** [comment]
@elliotxx  非常感谢，已经修复了🚀，确实是`KUBECONFIG `变量问题。
