### ISSUE TITLE
Bug: OpenAPI Document endpoint is wrong, now docs/images/index.html, expect docs/index.html

### ISSUE THREAD

**Issue by elliotxx** [KusionStack/karpor#577]
### What would you like to be added?

The OpenAPI Document endpoint is wrong, now `docs/images/index.html`, expect `docs/index.html`

### Why is this needed?

yeah

**Comment by elliotxx** [comment]
@regend Hi, can you leave a comment on this issue so that I can mark it as completed by you and you will appear on our https://github.com/KusionStack/karpor/issues/463!

**Comment by regend** [comment]
fix it on https://github.com/KusionStack/karpor/pull/600
