### ISSUE TITLE
helm 部署karpor 失败 karpor-syncer 启动失败报错7443端口连接失败

### ISSUE THREAD

**Issue by wenxuanwu** [KusionStack/karpor#608]
### Which jobs are failing?

使用离线环境进行部署
k8s 版本  1.17.5 版本
helm 版本3.5版本
存储类型使用本地hostpath 并创建pv

### Which tests are failing?

![karpor](https://github.com/user-attachments/assets/5c97c887-a00a-4e77-a3dd-b62e381d23e8)
报错日志
karporl#kubectl Logs-n karpor serving.go:342J Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt#apiserver Local.config/certificates/apiserver.key I0828 12:01:39.321776 ? E0828 12:01:39.325166 cLuster.go:1611 "Failed to get API Group-Resources'err-"Get"https://127.0.0.1:7443/api?timeout-32Sdialtcp 127.0.0.1:7443: connect: connection refused" E0828 2:01:39.325227 syncer-go:70]setup:unable to start managererr= Get https://127.0.0.1:7443/api?timeout-32s"dial tcp 27.0.0.1:7443: connect: connection refused" E0828 12:01:39.325251 run.go:741command failed" err="Get I"https://127.0.0.1:7443/api?timeout-32s|": dial tcp 127.0.0.1:7443: connect:connection refused

### Since when has it been failing?

helm执行后

### Reason for failure (if possible)

服务未正常启动

**Comment by elliotxx** [comment]
@wenxuanwu Hi 感谢反馈，请问你部署的时候 Job 已经完成了吗，如果已经完成还是报这个错误可能跟“存储类型使用本地hostpath 并创建pv” 有关系，我们需要验证下

**Comment by cx2c** [comment]
.kube kubectl logs -n karpor karpor-syncer-7649f7874c-vqwfz -f
I0903 03:28:31.407819       1 serving.go:342] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
E0903 03:28:31.411601       1 cluster.go:161] "Failed to get API Group-Resources" err="the server rejected our request for an unknown reason"
E0903 03:28:31.411629       1 syncer.go:70] "setup: unable to start manager" err="the server rejected our request for an unknown reason"
E0903 03:28:31.411651       1 run.go:74] "command failed" err="the server rejected our request for an unknown reason"

syncer 连不上 server
karpor-kubeconfig 中 server: karpor-server.karpor.svc:7443 有点问题 必须https 才能行。 估计是这个原因。

**Comment by elliotxx** [comment]
@cx2c 感谢反馈，是这个原因，最近的一次修复中漏掉了 https 前缀，我们修复下

**Comment by elliotxx** [comment]
@cx2c @wenxuanwu 这个问题已经彻底修复，我本地试了下没有问题了：

![image](https://github.com/user-attachments/assets/f5eb0ee4-8db0-4fd9-898a-1c567c200008)

可以升级到最新版本的 helm 包（目前是 v0.5.1），然后重新安装下。
```bash
helm repo update
helm upgrade karpor-release kusionstack/karpor
```

![image](https://github.com/user-attachments/assets/d849ad7c-b4bf-436c-be0f-61410787bac1)

**Comment by cx2c** [comment]
![image](https://github.com/user-attachments/assets/94662a39-d003-4351-98a4-af37fb50f089)

**Comment by cx2c** [comment]
![image](https://github.com/user-attachments/assets/66e4a42a-4366-40f2-a433-0b68d4b03c71)

这个版本不能展示 deployment 的yaml么。 怎么切换 都是显实cluster的yaml

**Comment by elliotxx** [comment]
@cx2c 收到，可能是最近引入的新问题，我们看下

**Comment by wenxuanwu** [comment]
> @cx2c @wenxuanwu 这个问题已经彻底修复，我本地试了下没有问题了：
> 
> ![image](https://private-user-images.githubusercontent.com/9360247/363838883-f5eb0ee4-8db0-4fd9-898a-1c567c200008.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTAyMDYsIm5iZiI6MTcyNTU4OTkwNiwicGF0aCI6Ii85MzYwMjQ3LzM2MzgzODg4My1mNWViMGVlNC04ZGIwLTRmZDktODk4YS0xYzU2N2MyMDAwMDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDZUMDIzMTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTJkZGE1NDI2MzJjMDdmY2Q2YzhiMTMxNThmZjU2MzBlNzMxMWI5ODBkN2Q4NTc4YmIwM2UwNGVmNzdhNGE0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0ntdRqB4iEpMCVtUMGVQF7MltSSiH7KYLFKkfgcOtkw)
> 
> 可以升级到最新版本的 helm 包（目前是 v0.5.1），然后重新安装下。
> 
> ```shell
> helm repo update
> helm upgrade karpor-release kusionstack/karpor
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/9360247/363838871-d849ad7c-b4bf-436c-be0f-61410787bac1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTAyMDYsIm5iZiI6MTcyNTU4OTkwNiwicGF0aCI6Ii85MzYwMjQ3LzM2MzgzODg3MS1kODQ5YWQ3Yy1iNGJmLTQzNmMtYmUwZi02MTQxMDc4N2JhYzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDZUMDIzMTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWUxNWZiM2FjOTMzNTdmZGQyYzEwNzQ5NzU0ZTU0M2E0NDFkZGM5ZDJjNmJiMDZhNDZlZTk2MTM1YTZkMWQzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dzIACrcJMNQAr8Ovwtu_s3xnTKUlNm-ykmxA64IwMOY)

使用阿里云的服务器尝试了一下，目前拉取不到镜像kusionstack/karpor:v0.5.1
![image](https://github.com/user-attachments/assets/43e835ce-a119-44ee-b98a-e7711e4ec7f1)

**Comment by ruquanzhao** [comment]
> ![image](https://private-user-images.githubusercontent.com/13431516/363864248-66e4a42a-4366-40f2-a433-0b68d4b03c71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDY5NzMsIm5iZiI6MTcyNjA0NjY3MywicGF0aCI6Ii8xMzQzMTUxNi8zNjM4NjQyNDgtNjZlNGE0MmEtNDM2Ni00MGYyLWE0MzMtMGI2OGQ0YjAzYzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA5MjQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0N2UzMGE3MDUxNTM0M2U2ZTZhYTk4NzA1YzZlM2U5ZTM0ZWUyMmYwYjI3YmY4Nzk5NGRmNzc2YmQwMTJlYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KUC6zmu8RSjwLnZlS7AZx-w9Q7mcPEwfYf8BuMsGn7o)
> 
> 这个版本不能展示 deployment 的yaml么。 怎么切换 都是显实cluster的yaml

@cx2c 这个bug已经修复啦，可以使用v0.5.2（对应的chart版本是0.6.9)

**Comment by cx2c** [comment]
> > ![image](https://private-user-images.githubusercontent.com/13431516/363864248-66e4a42a-4366-40f2-a433-0b68d4b03c71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDY5NzMsIm5iZiI6MTcyNjA0NjY3MywicGF0aCI6Ii8xMzQzMTUxNi8zNjM4NjQyNDgtNjZlNGE0MmEtNDM2Ni00MGYyLWE0MzMtMGI2OGQ0YjAzYzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA5MjQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0N2UzMGE3MDUxNTM0M2U2ZTZhYTk4NzA1YzZlM2U5ZTM0ZWUyMmYwYjI3YmY4Nzk5NGRmNzc2YmQwMTJlYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KUC6zmu8RSjwLnZlS7AZx-w9Q7mcPEwfYf8BuMsGn7o)
> > 这个版本不能展示 deployment 的yaml么。 怎么切换 都是显实cluster的yaml
> 
> @cx2c 这个bug已经修复啦，可以使用v0.5.2（对应的chart版本是0.6.9)


是不是还不太行

<img width="1685" alt="image" src="https://github.com/user-attachments/assets/4ff54ec8-4f45-46bb-b650-e5bd17a5e4ce">

**Comment by cx2c** [comment]
还有7443是加了自有tls证书吧，和我的ingress https证书冲突了。我应该怎么配置ingress

**Comment by elliotxx** [comment]
好的，这个 issue 就先 close 了，有问题可以再提 issue 反馈 👌
