### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by danielstankw** [KusionStack/karpor#611]
### What happened?

I created karpor namespace and try to deploy it with

`helm install karpor kusionstack/karpor`

but get

```bashrc
Error: INSTALLATION FAILED: Unable to continue with install: Namespace "karpor" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "karpor"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "karpor"
```

### What did you expect to happen?

.

### How can we reproduce it (as minimally and precisely as possible)?

.

### Anything else we need to know?

.

### Karpor version

<details>

```console
$ karpor -V
# paste output here
```

</details>
.

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

**Comment by ruquanzhao** [comment]
Hi, @danielstankw 👋
Maybe there is some dirty data in your cluster. You can use `helm list -A` to know if there is any previous version, then delete them(You may lost old data) and reinstall karpor.

**Comment by elliotxx** [comment]
@danielstankw Hi, Is there any problem now?
