### ISSUE TITLE
kubeaudit being deprecated, what next? 

### ISSUE THREAD

**Issue by haiwu** [KusionStack/karpor#616]
### What happened?

it seems this project using kubeaudit, which is being deprecated very soon. 

### What did you expect to happen?

project should use other OSS project that is not deprecated. 

### How can we reproduce it (as minimally and precisely as possible)?

see here: https://github.com/Shopify/kubeaudit

### Karpor version

n/a

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

**Comment by elliotxx** [comment]
Ohhh, thanks for your feedback. In addition to Kubeaudit, we also considered [kube-score](https://github.com/zegl/kube-score) in #454 . Of course, there must be a better option. Do you have any recommendations?
