### ISSUE TITLE
Feat: Real-time Pod Event Aggregator

### ISSUE THREAD

**Issue by elliotxx** [KusionStack/karpor#635]
## What would you like to be added?
A dynamic event aggregator for Pods that supports real-time refresh and event correlation.

## Why is this needed?
To provide users with a centralized view of Pod events across the cluster, making it easier to monitor and troubleshoot issues in real-time. This will help operators quickly identify and respond to Pod-related issues.

**Comment by ruquanzhao** [comment]
close since https://github.com/KusionStack/karpor/pull/659 is merged
