### ISSUE TITLE
'unknown revision v0.0.0' errors caused by the k8s.io/kube-aggregator

### ISSUE THREAD

**Issue by cheny-alf** [KusionStack/karpor#665]
### What happened?

When executing go list -m all multiple dependencies can not be resolved due to invalid versions. This command (with some additional flags) is used by JetBrain's GoLand to sync the dependencies and since the command fails, the IDE is not capable to resolve any dependency which results in a huge pile of errors per file.

<img width="976" alt="image" src="https://github.com/user-attachments/assets/0c26316f-57e3-4502-b552-cce1b72e1f5a" />

### What did you expect to happen?

null

### How can we reproduce it (as minimally and precisely as possible)?

Use the JetBrains GoLand ide to compile.

### Anything else we need to know?

This issue may be related to [kubernetes issues](https://github.com/kubernetes/cloud-provider-openstack/issues/2490)

### Karpor version

<details>

```console
$ karpor -V
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

**Comment by cheny-alf** [comment]
#666

**Comment by elliotxx** [comment]
@cheny-alf Yeah, adding `replace` can solve the Goland errors. Although the use of `replace` is not elegant, I cannot prevent Goland from executing the default command of `go list -m all`.

**Comment by elliotxx** [comment]
#666 Merged
